# Generated by Django 3.0.7 on 2020-06-09 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0003_auto_20200608_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('webhook_id', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Game')),
            ],
        ),
        migrations.CreateModel(
            name='DiscordPlayerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=255)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord', to='web.Player')),
            ],
        ),
    ]
