version: '3'
services:
  web:
    build: .
    ports:
      - "127.0.0.1:${HOST_PORT}:3031"
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASS}@postgresql/postgres"
      REDIS_URL: "redis"
      HOSTNAME:
      SECRET_KEY:
    depends_on:
      - "postgresql"
      - "redis"
  redis:
    image: "redis:alpine"
  postgresql:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}