# Generated by Django 3.0.7 on 2020-06-08 19:19

from django.db import migrations, models
import django.db.models.deletion


def migrate_player(apps, schema_editor):
    LastPlayerTurn = apps.get_model("web", "LastPlayerTurn")
    Player = apps.get_model('web', 'Player')
    for turn in LastPlayerTurn.objects.all():
        p, _ = Player.objects.get_or_create(name=turn.civilization_nick, defaults={'name': turn.civilization_nick})
        turn.player_id = p.pk
        turn.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lastplayerturn',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Player',
                                    null=True),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_player),
        migrations.RemoveField(
            model_name='lastplayerturn',
            name='civilization_nick',
        ),
    ]
