# Generated by Django 3.0.7 on 2020-06-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200608_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastplayerturn',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Player'),
        ),
    ]
